const mongoose = require('mongoose');

const menuItemSchema = new mongoose.Schema({
    restaurantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Restaurant', required: true },
    categoryId: { type: mongoose.Schema.Types.ObjectId, ref: 'MenuCategory', required: true },
    name: { type: String, required: true },
    description: { type: String, default: '' },
    price: { type: Number, required: true },
    image: { type: String, default: '' },
    tags: [{ type: String }],
    embedding: {
        type: [Number],
        default: [],
        // We will use this array to store the vector embeddings generated by Gemini
    }
}, { timestamps: true });

module.exports = mongoose.model('MenuItem', menuItemSchema);
